import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

import styles from "../styles/Home.module.css";
import { myLoader } from "../components/shared/customImageLoader";
import { Fable1 } from "../components/chapters/1";
import { Fable2 } from "../components/chapters/2";
import { Fable3 } from "../components/chapters/3";
import { Fable4 } from "../components/chapters/4";
import { Fable5 } from "../components/chapters/5";
import { Fable6 } from "../components/chapters/6";
import { Fable7 } from "../components/chapters/7";
import { Fable8 } from "../components/chapters/8";
import { Fable9 } from "../components/chapters/9";
import { Fable10 } from "../components/chapters/10";
import BasicLayout from "layout/Basic";
import { MainLayout } from "layout/MainLayout";

const Title = styled.h1`
  color: red;
  font-size: 16vmin;
  text-align: center;
  padding: 0.4em;

  @media only screen and (min-width: ${(props) => props.theme.breakpoints.md}) {
    font-size: 4em;
  }
`;

const SubTitle = styled.h2`
  color: red;
  font-size: 8vmin;
  text-align: center;
  padding: 0.4em;

  @media only screen and (min-width: ${(props) => props.theme.breakpoints.md}) {
    font-size: 2em;
  }
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Summary of The Richest Man In Babylon</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <BasicLayout>
        <MainLayout>
          <main>
            <Title>The Richest Man In Babylon</Title>
            <SubTitle>George S. Clason</SubTitle>

            <Fable1 title={"1"} />
            <Fable2 title={"2"} />
            <Fable3 title={"3"} />
            <Fable4 title={"4"} />
            <Fable5 title={"5"} />
            <Fable6 title={"6"} />
            <Fable7 title={"7"} />
            <Fable8 title={"8"} />
            <Fable9 title={"9"} />
            <Fable10 title={"10"} />
          </main>
        </MainLayout>
      </BasicLayout>
    </>
  );
};

export default Home;
