import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

import styles from "../styles/Home.module.css";
import { myLoader } from "../components/shared/customImageLoader";
import { Fable1 } from "../components/chapters/1";
import { Fable2 } from "../components/chapters/2";
import { Fable3 } from "../components/chapters/3";
import { Fable4 } from "../components/chapters/4";
import { Fable5 } from "../components/chapters/5";
import { Fable6 } from "../components/chapters/6";
import { Fable7 } from "../components/chapters/7";
import { Fable8 } from "../components/chapters/8";
import { Fable9 } from "../components/chapters/9";
import { Fable10 } from "../components/chapters/10";
import BasicLayout from "layout/Basic";

const Title = styled.h1`
  color: red;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
        <div id="layout">
          <main>
            <Title>The Richest Man In Babylon</Title>

            <Fable1 />
            <Fable2 />
            <Fable3 />
            <Fable4 />
            <Fable5 />
            <Fable6 />
            <Fable7 />
            <Fable8 />
            <Fable9 />
            <Fable10 />
          </main>
        </div>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Summarized with love by CMD Labs
            {/* <span className={styles.logo}>
            <Image
              loader={myLoader}
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span> */}
          </a>
        </footer>
      </BasicLayout>
    </div>
  );
};

export default Home;
